export const regionKeys = {
  uz: [
    ['Toshkent shahar', 'toshkent shahar'],
    ['Toshkent viloyai', 'toshkent viloyat'],
    ['Samarqand', 'samarqand'],
    ['Buxoro', 'buxoro'],
    ['Andijon', 'andijon'],
    ["Farg'ona", 'fargona'],
    ['Namangan', 'namangan'],
    ['Qashqadaryo', 'qashqadaryo'],
    ['Jizzax', 'jizzax'],
    ['Sirdaryo', 'sirdaryo'],
    ['Xorazm', 'xorazm'],
    ['Navoiy', 'navoiy'],
    ['Surxondaryo', 'surxondaryo'],
    ["Qoraqalpog'iston", 'qoraqalpogiston'],
  ],
  ru: [
    ['Город Ташкент', 'toshkent shahar'],
    ['Ташкентская область', 'toshkent viloyat'],
    ['Самарканд', 'samarqand'],
    ['Бухара', 'buxoro'],
    ['Андижан', 'andijon'],
    ['Фергана', 'fargona'],
    ['Наманган', 'namangan'],
    ['Кашкадарья', 'qashqadaryo'],
    ['Джизак', 'jizzax'],
    ['Сырдарья', 'sirdaryo'],
    ['Хорезм', 'xorazm'],
    ['Навои', 'navoiy'],
    ['Сурхандарья', 'surxondaryo'],
    ['Каракалпакстан', 'qoraqalpogiston'],
  ],
  en: [
    ['Tashkent city', 'toshkent shahar'],
    ['Tashkent region', 'toshkent viloyat'],
    ['Samarkand', 'samarqand'],
    ['Bukhara', 'buxoro'],
    ['Andijan', 'andijon'],
    ['Fergana', 'fargona'],
    ['Namangan', 'namangan'],
    ['Qashqadarya', 'qashqadaryo'],
    ['Jizzakh', 'jizzax'],
    ['Syrdarya', 'sirdaryo'],
    ['Khorezm', 'xorazm'],
    ['Navoiy', 'navoiy'],
    ['Surxondarya', 'surxondaryo'],
    ['Karakalpakstan', 'qoraqalpogiston'],
  ],
};

export const tashkentCitysKeys = {
  uz: [
    ['Bektemir', 'bektemir'],
    ['Chilonzor', 'chilonzor'],
    ['Mirobod', 'mirobod'],
    ['Mirzo Ulugbek', 'mirzo ulugbek'],
    ['Olmozor', 'olmazor'],
    ['Sergeli', 'sergeli'],
    ['Shayhontohur', 'shayhontohur'],
    ['Uchtepa', 'uchtepa'],
    ['Yakkasaroy', 'yakkasaroy'],
    ['Yashnaobod', 'yashnaobod'],
    ['Yangihayot', 'yangihayot'],
    ['Yunusobod', 'yunusobod'],
  ],
  ru: [
    ['Бектемир', 'bektemir'],
    ['Чиланзар', 'chilonzor'],
    ['Миробод', 'mirobod'],
    ['Мирзо Улугбек', 'mirzo ulugbek'],
    ['Олмазор', 'olmazor'],
    ['Сергелий', 'sergeli'],
    ['Шайхантахур', 'shayhontohur'],
    ['Учтепин', 'uchtepa'],
    ['Яккасарай', 'yakkasaroy'],
    ['Яшнобод', 'yashnaobod'],
    ['Янгиҳайот район', 'yangihayot'],
    ['Юнусабад', 'yunusobod'],
  ],
  en: [
    ['Bektemir', 'bektemir'],
    ['Chilonzor', 'chilonzor'],
    ['Mirobod', 'mirobod'],
    ['Mirzo Ulugbek', 'mirzo ulugbek'],
    ['Olmazor', 'olmazor'],
    ['Sergeli', 'sergeli'],
    ['Shayhontohur', 'shayhontohur'],
    ['Uchtepa', 'uchtepa'],
    ['Yakkasaroy', 'yakkasaroy'],
    ['Yashnaobod', 'yashnaobod'],
    ['Yangihayot', 'yangihayot'],
    ['Yunusobod', 'yunusobod'],
  ],
};

export const tashkentRegionCitysKeys = {
  uz: [
    ['Bekobod', 'bekobod'],
    ['Boʻka', 'boka'],
    ['Boʻstonliq', 'bostonliq'],
    ['Chinoz', 'chinoz'],
    ['Ohangaron', 'ohangaron'],
    ['Oqqoʻrgʻon', 'oqqorgon'],
    ['Oʻrta Chirchiq', 'ortachirchiq'],
    ['Parkent', 'parkent'],
    ['Piskent', 'piskent'],
    ['Qibray', 'qibray'],
    ['Quyi Chirchiq', 'quyichirchiq'],
    ['Toshkent', 'toshkent'],
    ['Yangiyoʻl', 'yangoyol'],
    ['Yuqori Chirchiq', 'yuqorichirchiq'],
    ['Zangiota', 'zangiota'],
  ],
  ru: [
    ['Бекабад', 'bekobod'],
    ['Бука', 'boka'],
    ['Бостонлик', 'bostonliq'],
    ['Чиноз', 'chinoz'],
    ['Оҳангарон', 'ohangaron'],
    ['Оққўрғон', 'oqqorgon'],
    ['Орта Чирчиқ', 'ortachirchiq'],
    ['Паркент', 'parkent'],
    ['Пискент', 'piskent'],
    ['Қибрай', 'qibray'],
    ['Қуйи Чирчиқ', 'quyichirchiq'],
    ['Тошкент', 'toshkent'],
    ['Янгиёл', 'yangoyol'],
    ['Юқори Чирчиқ', 'yuqorichirchiq'],
    ['Зангиотин', 'zangiota'],
  ],
  en: [
    ['Bekobod', 'bekobod'],
    ['Boka', 'boka'],
    ['Bostonliq', 'bostonliq'],
    ['Chinoz', 'chinoz'],
    ['Ohangaron', 'ohangaron'],
    ['Oqqorgon', 'oqqorgon'],
    ['Orta Chirchiq', 'ortachirchiq'],
    ['Parkent', 'parkent'],
    ['Piskent', 'piskent'],
    ['Qibray', 'qibray'],
    ['Quyi Chirchiq', 'quyichirchiq'],
    ['Toshkent', 'toshkent'],
    ['Yangiyol', 'yangoyol'],
    ['Yuqori Chirchiq', 'yuqorichirchiq'],
    ['Zangiota', 'zangiota'],
  ],
};

export const ferganaCitysKeys = {
  uz: [
    ['Bagʻdod', 'bogdod'],
    ['Beshariq', 'beshariq'],
    ['Buvayda', 'buvayda'],
    ['Dangʻara', 'dangara'],
    ['Fargʻona', 'fargona'],
    ['Furqat', 'furqat'],
    ['Oltiariq', 'oltiariq'],
    ['Oyim', 'oyim'],
    ['Oʻzbekiston', 'ozbekiston'],
    ['Qoʻshtepa', 'qoshtepa'],
    ['Quva', 'quva'],
    ['Rishton', 'rishton'],
    ['Soʻx', 'sox'],
    ['Toshloq', 'toshloq'],
    ['Uchkoʻprik', 'uchkoprik'],
    ['Voroshilov', 'voroshilov'],
    ['Yozyovon', 'yozyovon'],
  ],
  ru: [
    ['Багдод', 'bogdod'],
    ['Бешарык', 'beshariq'],
    ['Бувайдо', 'buvayda'],
    ['Дангарин', 'dangara'],
    ['Ферган', 'fargona'],
    ['Фуркат', 'furqat'],
    ['Олтарик', 'oltiariq'],
    ['Ойим', 'oyim'],
    ['Узбекистан', 'ozbekiston'],
    ['Қўштепа', 'qoshtepa'],
    ['Қува', 'quva'],
    ['Риштон', 'rishton'],
    ['Сох', 'sox'],
    ['Тошлок', 'toshloq'],
    ['Учкўприк', 'uchkoprik'],
    ['Ворошилов', 'voroshilov'],
    ['Ёзёвон', 'yozyovon'],
  ],
  en: [
    ['Bagdod', 'bogdod'],
    ['Beshariq', 'beshariq'],
    ['Buvayda', 'buvayda'],
    ['Dangara', 'dangara'],
    ['Fergana', 'fargona'],
    ['Furqat', 'furqat'],
    ['Oltiariq', 'oltiariq'],
    ['Oyim', 'oyim'],
    ['Ozbekiston', 'ozbekiston'],
    ['Qoshtepa', 'qoshtepa'],
    ['Quva', 'quva'],
    ['Rishton', 'rishton'],
    ['Sox', 'sox'],
    ['Toshloq', 'toshloq'],
    ['Uchkoprik', 'uchkoprik'],
    ['Voroshilov', 'voroshilov'],
    ['Yozyovon', 'yozyovon'],
  ],
};

export const samarkandCityKeys = {
  uz: [
    ['Samarqand', 'samarqand'],
    ['Ishtixon', 'ishtixon'],
    ['Jomboy', 'jomboy'],
    ['Urgut', 'urgut'],
    ['Kattakurgan', 'kattakurgan'],
    ['Pastdargom', 'pastdargom'],
    ['Narpay', 'narpay'],
    ['Payariq', 'payariq'],
    ['Bulungur', 'bulungur'],
    ['Oqdaryo', 'oqdaryo'],
    ['Toyloq', 'toyloq'],
    ['Qo‘shrabot', 'qoshrabot'],
    ['Nurobod', 'nurobod'],
    ['Paxtachi', 'paxtachi'],
    ['Oqdaryo', 'oqdaryo_tumani'],
  ],
  ru: [
    ['Самарканд округ', 'samarqand'],
    ['Иштыхан округ', 'ishtixon'],
    ['Джамбай округ', 'jomboy'],
    ['Ургут округ', 'urgut'],
    ['Каттакурган округ', 'kattakurgan'],
    ['Пастдаргом округ', 'pastdargom'],
    ['Нарпай округ', 'narpay'],
    ['Паярик округ', 'payariq'],
    ['Булунгур округ', 'bulungur'],
    ['Акдарья округ', 'oqdaryo'],
    ['Тойлак округ', 'toyloq'],
    ['Кушработ округ', 'qoshrabot'],
    ['Нурабад округ', 'nurobod'],
    ['Пахтачи округ', 'paxtachi'],
    ['Акдарья округ', 'oqdaryo_tumani'],
  ],
  en: [
    ['Samarkand', 'samarqand'],
    ['Ishtixon', 'ishtixon'],
    ['Jomboy', 'jomboy'],
    ['Urgut', 'urgut'],
    ['Kattakurgan', 'kattakurgan'],
    ['Pastdargom', 'pastdargom'],
    ['Narpay', 'narpay'],
    ['Payariq', 'payariq'],
    ['Bulungur', 'bulungur'],
    ['Oqdaryo', 'oqdaryo'],
    ['Toyloq', 'toyloq'],
    ['Qo‘shrabot', 'qoshrabot'],
    ['Nurobod', 'nurobod'],
    ['Paxtachi', 'paxtachi'],
    ['Oqdaryo', 'oqdaryo_tumani'],
  ],
};

export const bukharaCityKeys = {
  uz: [
    ['Buxoro', 'bukhara'],
    ['G‘ijduvon', 'gijduvon'],
    ['Kogon', 'kogon'],
    ['Olot', 'olot'],
    ['Jondor', 'jondor'],
    ['Kogon', 'kogon'],
    ['Peshku', 'peshku'],
    ['Qorako‘l', 'qorakol'],
    ['Qorovulbozor', 'qorovulbozor'],
    ['Romitan', 'romitan'],
    ['Shofirkon', 'shofirkon'],
    ['Vobkent', 'vobkent'],
  ],
  ru: [
    ['Бухара округ', 'bukhara'],
    ['Гиждуван округ', 'gijduvon'],
    ['Когон округ', 'kogon'],
    ['Олот округ', 'olot'],
    ['Джондор округ', 'jondor'],
    ['Когон округ', 'kogon'],
    ['Пешку округ', 'peshku'],
    ['Каракуль округ', 'qorakol'],
    ['Караулбазар округ', 'qorovulbozor'],
    ['Ромитан округ', 'romitan'],
    ['Шофиркон округ', 'shofirkon'],
    ['Вабкент округ', 'vobkent'],
  ],
  en: [
    ['Bukhara', 'bukhara'],
    ['Gijduvon', 'gijduvon'],
    ['Kogon', 'kogon'],
    ['Olot', 'olot'],
    ['Jondor', 'jondor'],
    ['Kogon', 'kogon'],
    ['Peshku', 'peshku'],
    ['Qorakol', 'qorakol'],
    ['Qorovulbozor', 'qorovulbozor'],
    ['Romitan', 'romitan'],
    ['Shofirkon', 'shofirkon'],
    ['Vobkent', 'vobkent'],
  ],
};

export const namanganCityKeys = {
  uz: [
    ['Chortoq', 'chortoq'],
    ['Chust', 'chust'],
    ['Kosonsoy', 'kosonsoy'],
    ['Mingbuloq', 'mingbuloq'],
    ['Namangan', 'namangan'],
    [' Norin', 'norin'],
    ['Pop', 'pop'],
    ['Toʻraqoʻrgʻon', 'toraqorgon'],
    ['Uchqoʻrgʻon', 'uchqorgon'],
    ['Uychi', 'uychi'],
    ['Yangiqoʻrgʻon', 'yangiqorgon'],
    ['Yangi Namangan', 'yanginamangan'],
  ],
  ru: [
    ['Чартак', 'chortoq'],
    ['Чуст', 'chust'],
    ['Косонсой', 'kosonsoy'],
    ['Мингбулак', 'mingbuloq'],
    ['Наманган', 'namangan'],
    ['Нарын', 'norin'],
    ['Поп', 'pop'],
    ['Туракурган', 'toraqorgon'],
    ['Учкурган', 'uchqorgon'],
    ['Уйчин', 'uychi'],
    ['Янгикурган', 'yangiqorgon'],
    ['Янги Наманган', 'yanginamangan'],
  ],
  en: [
    ['Chortoq', 'chortoq'],
    ['Chust', 'chust'],
    ['Kosonsoy', 'kosonsoy'],
    ['Mingbuloq', 'mingbuloq'],
    ['Namangan', 'namangan'],
    ['Norin', 'norin'],
    ['Pop', 'pop'],
    ['Toraqorgon', 'toraqorgon'],
    ['Uchqorgon', 'uchqorgon'],
    ['Uychi', 'uychi'],
    ['Yangiqorgon', 'yangiqorgon'],
    ['Yangi Namangan', 'yanginamangan'],
  ],
};

export const andijanCityKeys = {
  uz: [
    ['Andijon', 'andijon'],
    ['Asaka', 'asaka'],
    ['Baliqchi', 'baliqchi'],
    ["Bo'ston", 'boz'],
    ['Buloqboshi', 'buloqboshi'],
    ['Izboskan', 'izboskan'],
    ['Jalaquduq', 'jalaquduq'],
    ['Xo‘jaobod', 'xojaobod'],
    ['Qo‘rg‘ontepa', 'qorgontepa'],
    ['Marhamat', 'marhamat'],
    ['Oltinko‘l', 'oltinkol'],
    ['Paxtaobod', 'paxtaobod'],
    ['Shahrixon', 'shahrixon'],
    ['Ulug‘nor', 'ulugnor'],
  ],
  ru: [
    ['Андижан', 'andijon'],
    ['Асакин', 'asaka'],
    ['Балыкчин', 'baliqchi'],
    ['Бостон', 'boz'],
    ['Булокбошин', 'buloqboshi'],
    ['Избоскан', 'izboskan'],
    ['Джалакудук', 'jalaquduq'],
    ['Мархамат', 'marhamat'],
    ['Алтынкуль', 'oltinkol'],
    ['Пахтаабад', 'paxtaobod'],
    ['Кургантепин', 'qorgontepa'],
    ['Шахрихан', 'shahrixon'],
    ['Улугнор', 'ulugnor'],
    ['Ходжаабад район', 'xojaobod'],
  ],
  en: [
    ['Andijan', 'andijon'],
    ['Asaka', 'asaka'],
    ['Baliqchi', 'baliqchi'],
    ['Boston', 'boz'],
    ['Buloqboshi', 'buloqboshi'],
    ['Izboskan', 'izboskan'],
    ['Jalaquduq', 'jalaquduq'],
    ['Marhamat', 'marhamat'],
    ['Oltinko‘l', 'oltinkol'],
    ['Paxtaobod', 'paxtaobod'],
    ['Qo‘rg‘ontepa', 'qorgontepa'],
    ['Shahrixon', 'shahrixon'],
    ['Ulug‘nor', 'ulugnor'],
    ['Xo‘jaobod', 'xojaobod'],
  ],
};

export const qashqadaryaCityKeys = {
  uz: [
    ['Bahoriston', 'bahoriston'],
    ['Chiroqchi', 'chiroqchi'],
    ['Dehqonobod', 'dehqonobod'],
    ['Gʻuzor', 'guzor'],
    ['Kasbi', 'kasbi'],
    ['Kitob', 'kitob'],
    ['Koson', 'koson'],
    ['Koʻkdala', 'kokdala'],
    ['Mirishkor', 'mirishkor'],
    ['Muborak', 'muborak'],
    ['Nishon', 'nishon'],
    ['Qamashi', 'qamashi'],
    ['Qarshi', 'qarshi'],
    ['Shahrisabz', 'shahrisabz'],
    ['Yakkabogʻ', 'yakkabog'],
  ],
  ru: [
    ['Бахористон', 'bahoriston'],
    ['Чиракчин', 'chiroqchi'],
    ['Дехканабад', 'dehqonobod'],
    ['Гузар', 'guzor'],
    ['Касбин', 'kasbi'],
    ['Китаб', 'kitob'],
    ['Касан', 'koson'],
    ['Кукдалин', 'kokdala'],
    ['Миришкор', 'mirishkor'],
    ['Мубарек', 'muborak'],
    ['Нишан', 'nishon'],
    ['Камашин', 'qamashi'],
    ['Каршин', 'qarshi'],
    ['Шахрисабз', 'shahrisabz'],
    ['Яккабог', 'yakkabog'],
  ],
  en: [
    ['Bahoriston', 'bahoriston'],
    ['Chiroqchi', 'chiroqchi'],
    ['Dehqonobod', 'dehqonobod'],
    ['Guzor', 'guzor'],
    ['Kasbi', 'kasbi'],
    ['Kitob', 'kitob'],
    ['Koson', 'koson'],
    ['Kokdala', 'kokdala'],
    ['Mirishkor', 'mirishkor'],
    ['Muborak', 'muborak'],
    ['Nishon', 'nishon'],
    ['Qamashi', 'qamashi'],
    ['Qarshi', 'qarshi'],
    ['Shahrisabz', 'shahrisabz'],
    ['Yakkabog', 'yakkabog'],
  ],
};

export const jizzaxCityKeys = {
  uz: [
    ['Jizzax', 'jizzax'],
    ['Arnasoy', 'arnasoy'],
    ['Baxmal', 'baxmal'],
    ['Do‘stlik', 'dostlik'],
    ['Forish', 'forish'],
    ['G‘allaorol', 'gallaorol'],
    ['Sharof Rashidov', 'sharof_rashidov'],
    ['Mirzacho‘l', 'mirzachol'],
    ['Paxtakor', 'paxtakor'],
    ['Yangiobod', 'yangiobod'],
    ['Zafarobod', 'zafarobod'],
    ['Zarbdor', 'zarbdor'],
  ],
  ru: [
    ['Джизак', 'jizzax'],
    ['Арнасай', 'arnasoy'],
    ['Бахмаль', 'baxmal'],
    ['Дустлик', 'dostlik'],
    ['Фариш', 'forish'],
    ['Галлаараль', 'gallaorol'],
    ['Шароф Рашидов район', 'sharof_rashidov'],
    ['Мирзачуль', 'mirzachol'],
    ['Пахтакор', 'paxtakor'],
    ['Янгиабад', 'yangiobod'],
    ['Зафарабад', 'zafarobod'],
    ['Зарбдор', 'zarbdor'],
  ],
  en: [
    ['Jizzax', 'jizzax'],
    ['Arnasoy', 'arnasoy'],
    ['Baxmal', 'baxmal'],
    ['Dostlik', 'dostlik'],
    ['Forish', 'forish'],
    ['Gallaorol', 'gallaorol'],
    ['Sharof Rashidov', 'sharof_rashidov'],
    ['Mirzachol', 'mirzachol'],
    ['Paxtakor', 'paxtakor'],
    ['Yangiobod', 'yangiobod'],
    ['Zafarobod', 'zafarobod'],
    ['Zarbdor', 'zarbdor'],
  ],
};

export const sirdaryoCityKeys = {
  uz: [
    ['Sirdaryo', 'sirdaryo'],
    ['Boyovut', 'boyovut'],
    ['Guliston', 'guliston'],
    ['Mirzaobod', 'mirzaobod'],
    ['Oqoltin', 'oqoltin'],
    ['Sayxunobod', 'sayxunobod'],
    ['Sardoba', 'sardoba'],
    ['Xovos', 'xovos'],
    ['Yangiyer', 'yangiyer'],
  ],
  ru: [
    ['Сырдарьин', 'sirdaryo'],
    ['Баяут', 'boyovut'],
    ['Гулистан', 'guliston'],
    ['Мирзаабад', 'mirzaobod'],
    ['Акалтын', 'oqoltin'],
    ['Сайхунабад', 'sayxunobod'],
    ['Сардобин', 'sardoba'],
    ['Хавас', 'xovos'],
    ['Янгиер', 'yangiyer'],
  ],
  en: [
    ['Sirdaryo', 'sirdaryo'],
    ['Boyovut', 'boyovut'],
    ['Guliston', 'guliston'],
    ['Mirzaobod', 'mirzaobod'],
    ['Oqoltin', 'oqoltin'],
    ['Sayxunobod', 'sayxunobod'],
    ['Sardoba', 'sardoba'],
    ['Xovos', 'xovos'],
    ['Yangiyer', 'yangiyer'],
  ],
};

export const xorazmCityKeys = {
  uz: [
    ['Urganch', 'urganch'],
    ['Bogʻot', 'bogot'],
    ['Gurlan', 'gurlan'],
    ['Xiva', 'xiva'],
    ['Xonqa', 'xonqa'],
    ['Hazorasp', 'hazorasp'],
    ['Shovot', 'shovot'],
    ['Yangiariq', 'yangiariq'],
    ['Yangibozor', 'yangibozor'],
    ['Qoʻshkoʻpir', 'qoshkoprik'],
    ['Tuproqqalʼa', 'tuproqqala'],
  ],
  ru: [
    ['Ургенч', 'urganch'],
    ['Багат', 'bogot'],
    ['Гурлан', 'gurlan'],
    ['Хивин', 'xiva'],
    ['Ханкин', 'xonqa'],
    ['Хазарасп', 'hazorasp'],
    ['Шават', 'shovot'],
    ['Янгиарик', 'yangiariq'],
    ['Янгибазар', 'yangibozor'],
    ['Кошкупыр', 'qoshkoprik'],
    ['Тупраккалин', 'tuproqqala'],
  ],
  en: [
    ['Urganch', 'urganch'],
    ['Bogot', 'bogot'],
    ['Gurlan', 'gurlan'],
    ['Xiva', 'xiva'],
    ['Xonqa', 'xonqa'],
    ['Hazorasp', 'hazorasp'],
    ['Shovot', 'shovot'],
    ['Yangiariq', 'yangiariq'],
    ['Yangibozor', 'yangibozor'],
    ['Qoshkoprik', 'qoshkoprik'],
    ['Tuproqqala', 'tuproqqala'],
  ],
};

export const surxandaryaCityKeys = {
  uz: [
    ['Angor', 'angor'],
    ['Bandixon', 'bandixon'],
    ['Boysun', 'boysun'],
    ['Denov', 'denov'],
    ['Jarqoʻrgʻon', 'jarqorgon'],
    ['Qiziriq', 'qiziriq'],
    ['Qumqoʻrgʻon', 'qumqoron'],
    ['Muzrabod', 'muzrabod'],
    ['Oltinsoy', 'oltinsoy'],
    ['Sariosiyo', 'sariosiyo'],
    ['Sherobod', 'sherobod'],
    ['Shoʻrchi', 'shorchi'],
    ['Termiz', 'termiz'],
    ['Uzun', 'uzun'],
  ],
  ru: [
    ['Ангор', 'angor'],
    ['Бандихан', 'bandixon'],
    ['Байсун', 'boysun'],
    ['Денау', 'denov'],
    ['Джаркурган', 'jarqorgon'],
    ['Кызырык', 'qiziriq'],
    ['Кумкурган', 'qumqoron'],
    ['Музрабад', 'muzrabod'],
    ['Алтынсай', 'oltinsoy'],
    ['Сариасий', 'sariosiyo'],
    ['Шерабад', 'sherobod'],
    ['Шурчин', 'shorchi'],
    ['Термез', 'termiz'],
    ['Узун', 'uzun'],
  ],
  en: [
    ['Angor', 'angor'],
    ['Bandixon', 'bandixon'],
    ['Boysun', 'boysun'],
    ['Denov', 'denov'],
    ['Jarqoʻrgʻon', 'jarqorgon'],
    ['Qiziriq', 'qiziriq'],
    ['Qumqoʻrgʻon', 'qumqoron'],
    ['Muzrabod', 'muzrabod'],
    ['Oltinsoy', 'oltinsoy'],
    ['Sariosiyo', 'sariosiyo'],
    ['Sherobod', 'sherobod'],
    ['Shoʻrchi', 'shorchi'],
    ['Termiz', 'termiz'],
    ['Uzun', 'uzun'],
  ],
};

export const karakalpakstanCityKeys = {
  uz: [
    ['Amudaryo', 'amudaryo'],
    ['Beruniy', 'beruniy'],
    ['Chimboy', 'chimboy'],
    ['Ellikqala', 'ellikqala'],
    ['Kegeyli', 'kegeyli'],
    ['Moʻynoq', 'moynoq'],
    ['Nukus', 'nukus'],
    ['Qanlikoʻl', 'qanlikol'],
    ['Qoʻngʻirot', 'qongirot'],
    ['Qoraoʻzak', 'qoraozak'],
    ['Shumanay', 'shumanay'],
    ['Taxtakoʻpir', 'taxtakopir'],
    ['Toʻrtkoʻl', 'tortkol'],
    ['Xoʻjayli', 'xojayli'],
  ],
  ru: [
    ['Амударьин', 'amudaryo'],
    ['Беруни', 'beruniy'],
    ['Чимбай', 'chimboy'],
    ['Элликкалин', 'ellikqala'],
    ['Кегейлий', 'kegeyli'],
    ['Муйнак', 'moynoq'],
    ['Нукус', 'nukus'],
    ['Канлыкуль', 'qanlikol'],
    ['Кунград', 'qongirot'],
    ['Караузяк', 'qoraozak'],
    ['Шуманай', 'shumanay'],
    ['Тахтакупыр', 'taxtakopir'],
    ['Турткуль', 'tortkol'],
    ['Ходжейлий', 'xojayli'],
  ],
  en: [
    ['Amudaryo', 'amudaryo'],
    ['Beruniy', 'beruniy'],
    ['Chimboy', 'chimboy'],
    ['Ellikqala', 'ellikqala'],
    ['Kegeyli', 'kegeyli'],
    ['Moʻynoq', 'moynoq'],
    ['Nukus', 'nukus'],
    ['Qanlikoʻl', 'qanlikol'],
    ['Qoʻngʻirot', 'qongirot'],
    ['Qoraoʻzak', 'qoraozak'],
    ['Shumanay', 'shumanay'],
    ['Taxtakoʻpir', 'taxtakopir'],
    ['Toʻrtkoʻl', 'tortkol'],
    ['Xoʻjayli', 'xojayli'],
  ],
};

export const navoiCityKeys = {
  uz: [
    ['Konimex', 'konimex'],
    ['Karmana', 'karmana'],
    ['Qiziltepa', 'qiziltepa'],
    ['Xatirchi', 'xatirchi'],
    ['Navbahor', 'navbahor'],
    ['Nurota', 'nurota'],
    ['Tomdi', 'tomdi'],
    ['Uchquduq', 'uchquduq'],
  ],
  ru: [
    ['Конимех', 'konimex'],
    ['Карманин', 'karmana'],
    ['Кызылтепин', 'qiziltepa'],
    ['Хатырчин', 'xatirchi'],
    ['Навбахор', 'navbahor'],
    ['Нуротин', 'nurota'],
    ['Томдин', 'tomdi'],
    ['Учкудук', 'uchquduq'],
  ],
  en: [
    ['Konimex', 'konimex'],
    ['Karmana', 'karmana'],
    ['Qiziltepa', 'qiziltepa'],
    ['Xatirchi', 'xatirchi'],
    ['Navbahor', 'navbahor'],
    ['Nurota', 'nurota'],
    ['Tomdi', 'tomdi'],
    ['Uchquduq', 'uchquduq'],
  ],
};
